// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://2zv73d2u3bhvvmcagqbgczem4m.appsync-api.us-east-2.amazonaws.com/graphql',
          region: 'us-east-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-d7bsfpyonjc6ljz7yqufbtol7y'
        }
    }
};

export default config;