/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://aakxw5fivnbt5agxypux7o4kdq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pbp4bvdb5ndbdf6i4ozxf5pbba",
    "aws_cognito_identity_pool_id": "us-east-2:b7738cba-0b29-450e-a7bf-1fa37c8c6930",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_B3bhHidNT",
    "aws_user_pools_web_client_id": "7b3csc5oo08ia04a50glao5n2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
